//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Activity
{
    public int activity_id { get; set; }
    public string activity_name { get; set; }
    public string activity_content { get; set; }
    public System.DateTime activity_start { get; set; }
    public System.DateTime activity_end { get; set; }
    public string activity_cover { get; set; }
    public string activity_coverlable { get; set; }
    public Nullable<int> activity_topicid { get; set; }
    public Nullable<int> activity_hot { get; set; }
    public string activity_topicname { get; set; }
    public int activity_class { get; set; }

    public virtual Topic Topic { get; set; }
}

public partial class Admin
{
    public Admin()
    {
        this.Question = new HashSet<Question>();
    }

    public int id { get; set; }
    public string username { get; set; }
    public string nickname { get; set; }
    public string password { get; set; }
    public string email { get; set; }
    public string photo { get; set; }

    public virtual ICollection<Question> Question { get; set; }
}

public partial class Column
{
    public Column()
    {
        this.News = new HashSet<News>();
    }

    public int column_id { get; set; }
    public string column_title { get; set; }
    public string column_content { get; set; }
    public string column_cover { get; set; }
    public int column_hot { get; set; }
    public int column_like { get; set; }
    public System.DateTime column_time { get; set; }

    public virtual ICollection<News> News { get; set; }
}

public partial class Interest
{
    public int interest_id { get; set; }
    public string interest_title { get; set; }
    public string interest_content { get; set; }
    public System.DateTime interest_time { get; set; }
    public int interest_like { get; set; }
    public string interest_url { get; set; }
}

public partial class News
{
    public News()
    {
        this.Top = new HashSet<Top>();
    }

    public int news_id { get; set; }
    public string news_title { get; set; }
    public string news_content { get; set; }
    public System.DateTime news_time { get; set; }
    public int news_top { get; set; }
    public string news_cover { get; set; }
    public int news_class { get; set; }
    public int news_like { get; set; }
    public int news_hot { get; set; }
    public int new_column { get; set; }
    public string new_author { get; set; }

    public virtual Column Column { get; set; }
    public virtual News_class News_class1 { get; set; }
    public virtual ICollection<Top> Top { get; set; }
}

public partial class News_class
{
    public News_class()
    {
        this.News = new HashSet<News>();
    }

    public int news_classid { get; set; }
    public string news_classname { get; set; }

    public virtual ICollection<News> News { get; set; }
}

public partial class Question
{
    public int id { get; set; }
    public int user_id { get; set; }
    public string question1 { get; set; }
    public string answer { get; set; }
    public int question_id { get; set; }

    public virtual Admin Admin { get; set; }
}

public partial class Rumor
{
    public int rumor_id { get; set; }
    public string rumor_title { get; set; }
    public string rumor_content { get; set; }
    public System.DateTime rumor_time { get; set; }
    public int rumor_state { get; set; }
    public int rumor_hot { get; set; }
    public int rumor_like { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Top
{
    public int top_id { get; set; }
    public string top_path { get; set; }
    public int top_news { get; set; }
    public string top_cover { get; set; }

    public virtual News News { get; set; }
}

public partial class Topic
{
    public Topic()
    {
        this.Activity = new HashSet<Activity>();
    }

    public int topic_id { get; set; }
    public string topic_name { get; set; }
    public string topic_content { get; set; }
    public string topic_cover { get; set; }

    public virtual ICollection<Activity> Activity { get; set; }
}
